/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagename.view;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author cbcardoso
 */
public class MainForm extends javax.swing.JFrame
{
    
    private List<File> listOfFiles = new ArrayList<>();
    private Random randomGenerator = new Random();
    private String fileName;

    /**
     * Creates new form MainForm
     */
    public MainForm()
    {
        initComponents();
        fillFileList();
        chooseRandomImage();
    }
    
    private void fillFileList()
    {
        File folder = new File("images");
        File[] arrayOfFiles = folder.listFiles();
        
        for (int i = 0; i < arrayOfFiles.length; i++)
        {
            if (arrayOfFiles[i].isFile())
            {                
                String filename = arrayOfFiles[i].getName().toLowerCase();
                if (filename.endsWith(".jpg") || filename.endsWith(".jpeg"))
                {
                    System.out.println("File " + arrayOfFiles[i].getPath());
                    listOfFiles.add(arrayOfFiles[i]);
                }
            }
        }
    }
    
    private void chooseRandomImage()
    {
        int index = randomGenerator.nextInt(listOfFiles.size());
        lbImage.setIcon(new ImageIcon(listOfFiles.get(index).getPath()));        
        lbImage.updateUI();
        fileName = listOfFiles.get(index).getName().replaceFirst("[.][^.]+$", "");
    }
    
    private void compareName(String digitedName)
    {
        if (fileName.equalsIgnoreCase(digitedName))
        {
            lbResult.setText(fileName);
            chooseRandomImage();
        } else
        {
            lbResult.setText("NOPE");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lbImage = new javax.swing.JLabel();
        tfNomeDoArquivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbImage.setBackground(java.awt.Color.white);
        lbImage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tfNomeDoArquivo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                tfNomeDoArquivoActionPerformed(evt);
            }
        });
        tfNomeDoArquivo.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                tfNomeDoArquivoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                tfNomeDoArquivoKeyReleased(evt);
            }
        });

        jLabel3.setText("Digite o nome da imagem:");

        lbResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbResult.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeDoArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                    .addComponent(lbResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeDoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeDoArquivoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfNomeDoArquivoActionPerformed
    {//GEN-HEADEREND:event_tfNomeDoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeDoArquivoActionPerformed

    private void tfNomeDoArquivoKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNomeDoArquivoKeyPressed
    {//GEN-HEADEREND:event_tfNomeDoArquivoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeDoArquivoKeyPressed

    private void tfNomeDoArquivoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfNomeDoArquivoKeyReleased
    {//GEN-HEADEREND:event_tfNomeDoArquivoKeyReleased
        // TODO add your handling code here:
        compareName(tfNomeDoArquivo.getText());
    }//GEN-LAST:event_tfNomeDoArquivoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbResult;
    private javax.swing.JTextField tfNomeDoArquivo;
    // End of variables declaration//GEN-END:variables
}
